<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSavg43r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSavg43r/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSavg43r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSavg43r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSavg43r\appProdProjectContainer([
    'container.build_hash' => 'Savg43r',
    'container.build_id' => '912183ce',
    'container.build_time' => 1678114979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSavg43r');
